apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace toot-community

helmGlobals:
  chartHome: ../../../../../charts
  
resources:
  - ../../base
  - ../../base/search-cluster.yaml
  - secrets.yaml
  - database-rw-pooler.yaml
helmCharts:
  - name: redis-ha
    valuesFile: ../../base/helm-values/redis-ha.yaml
    additionalValuesFiles:
      - helm-values/redis-ha.yaml
    releaseName: redis-ha
    version: 4.35.10
    namespace: *namespace
    repo: https://dandydeveloper.github.io/charts
  - name: mastodon
    version: "0.0.0"
    releaseName: mastodon
    namespace: *namespace
    valuesFile: ../../base/helm-values/mastodon.yaml
    additionalValuesFiles:
      - helm-values/mastodon.yaml
  - name: varnish
    version: "0.0.0"
    releaseName: varnish-for-app
    namespace: *namespace
    valuesFile: ../../base/helm-values/varnish-for-app.yaml
    additionalValuesFiles:
      - helm-values/varnish-for-app.yaml
  - name: varnish
    version: "0.0.0"
    releaseName: varnish-for-static
    namespace: *namespace
    valuesFile: ../../base/helm-values/varnish-for-static.yaml
    additionalValuesFiles:
      - helm-values/varnish-for-static.yaml

images:
  - name: ghcr.io/mastodon/mastodon
    newTag: "v4.5.8@sha256:31504587a5cb72c04682ee020adef711c4fa765cc8d2b6cde1dec865adb2d718"
  - name: ghcr.io/mastodon/mastodon-streaming
    newTag: "v4.5.8@sha256:531cd86048273d38d621f88ad0355b65f7503b2166a205ef27d58c900b710026"
  - name: varnish
    newTag: "8.0.1@sha256:27fe28746312f82899ef3641365858cfd057ed177db6e986ecfc9896868b59eb"
 
patches:
  - path: database-cluster.yaml
  # - path: ../../base/patches/redis-ha-haproxy-affinity.yaml
  - target:
      name: elasticsearch
      kind: Elasticsearch
    patch: |-
      - op: replace
        path: /spec/nodeSets/0/podTemplate/spec/containers/0/resources
        value: 
          requests:
            cpu: '300m'
            memory: 4Gi
          limits:
            memory: 4Gi
      - op: replace
        path: /spec/nodeSets/0/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 40Gi
