apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace toot-community

helmGlobals:
  chartHome: ../../../../../charts
  
resources:
  - ../../base
  - ../../base/search-cluster.yaml
  - vault-auth.yaml
  - database-s3-credentials.yaml
  - database-rw-pooler.yaml
helmCharts:
  - name: redis-ha
    valuesFile: ../../base/helm-values/redis-ha.yaml
    additionalValuesFiles:
      - helm-values/redis-ha.yaml
    releaseName: redis-ha
    version: 4.35.10
    namespace: *namespace
    repo: https://dandydeveloper.github.io/charts
  - name: mastodon
    version: "0.0.0"
    releaseName: mastodon
    namespace: *namespace
    valuesFile: ../../base/helm-values/mastodon.yaml
    additionalValuesFiles:
      - helm-values/mastodon.yaml
  - name: varnish
    version: "0.0.0"
    releaseName: varnish-for-app
    namespace: *namespace
    valuesFile: ../../base/helm-values/varnish-for-app.yaml
    additionalValuesFiles:
      - helm-values/varnish-for-app.yaml

images:
  - name: ghcr.io/mastodon/mastodon
    newTag: "v4.5.9@sha256:2f4930e3f84a2f6b90b49c4e58329e9abc8bd354344cbd0607484514decff99f"
  - name: ghcr.io/mastodon/mastodon-streaming
    newTag: "v4.5.9@sha256:f118e0b14e271db534795c9cccdb1dc2dbf1bc32e8a9827d445238ab5d6b6303"
  - name: varnish
    newTag: "8.0.1@sha256:7fa8dd2fcdbeaefc29efb96c92dac505eb76ff194593db28632f687ad20ec230"
 
patches:
  - path: database-cluster.yaml
  # - path: ../../base/patches/redis-ha-haproxy-affinity.yaml
  - target:
      name: elasticsearch
      kind: Elasticsearch
    patch: |-
      - op: replace
        path: /spec/nodeSets/0/podTemplate/spec/containers/0/resources
        value: 
          requests:
            cpu: '300m'
            memory: 4Gi
          limits:
            memory: 4Gi
      - op: replace
        path: /spec/nodeSets/0/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 40Gi
