apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: longhorn-backups-credentials
  namespace: longhorn-system
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: longhorn/longhorn-backups-credentials
  refreshAfter: "1h"
  destination:
    name: longhorn-backups-credentials
    create: true
    overwrite: true
