apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n 

resources:
  - configuration.yaml
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: n8nio/n8n
    newTag: 1.115.2@sha256:ca7bc6b8de1b4f0f87e66d1fee70ddeafa4cc98989c361f7ec1a6c45bec04c96