apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n 

resources:
  - configuration.yaml
  - database.yaml
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: n8nio/n8n
    newTag: 2.11.0@sha256:fd27ead55b0c98a8e8322b7995c08603ceb515068498840a34fbb46329f81fcc
