apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n 

resources:
  - configuration.yaml
  - database.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml

images:
  - name: n8nio/n8n
    newTag: 2.6.2@sha256:ff6fe9eca746b7455c9e6e4fbc6f5753c3204e82279e015fa62f1bfe309e6343
