apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: n8n/n8n-secrets
  refreshAfter: "1h"
  destination:
    name: n8n-secrets
    create: true
    overwrite: true
