apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-public-credentials
  namespace: cloudflared
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: cloudflared/cloudflared-public-credentials
  refreshAfter: "1h"
  rolloutRestartTargets:
    - kind: Deployment
      name: cloudflared-public
  destination:
    name: cloudflared-public-credentials
    create: true
    overwrite: true
