apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: talos-ccm/hcloud
  refreshAfter: "1h"
  destination:
    name: hcloud
    create: true
    overwrite: true
