apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - namespace.yaml
  - vault-auth.yaml
  - secrets
  - jobs
  - nodes
  - storageclasses
  - rules.yaml

patches:
  - target:
      kind: Service
      name: longhorn-frontend
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: longhorn-frontend
        labels:
          teleport.dev/enabled: "true"
          domain: toot-community
        annotations:
          teleport.dev/name: tc-longhorn
          teleport.dev/port: "80"
          teleport.dev/protocol: http
          teleport.dev/description: "Longhorn distributed storage management"

helmCharts:
  - name: longhorn
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml
    version: "1.11.1"
    repo: https://charts.longhorn.io/
