apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: robusta-secrets-env
  namespace: robusta
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: robusta/robusta-secrets-env
  refreshAfter: "1h"
  destination:
    name: robusta-secrets-env
    create: true
    overwrite: true
