apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: robusta
spec:
  vaultConnectionRef: vault/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: robusta
    serviceAccount: default
  vaultAuthGlobalRef:
    name: default
    namespace: vault
    allowDefault: true
