apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: vault
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault
    serviceAccount: default
  vaultAuthGlobalRef:
    name: default
    namespace: vault
    allowDefault: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-metrics-token
  namespace: vault
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: vault/metrics-token
  refreshAfter: "1h"
  destination:
    name: vault-metrics-token
    create: true
    overwrite: true
