apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: database-s3-credentials
  namespace: microblog-network
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: microblog-network/database-s3-credentials
  refreshAfter: "1h"
  destination:
    name: database-s3-credentials
    create: true
    overwrite: true
