apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: database-pooler-rw
spec:
  instances: 2
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: database-backup
spec:
  configuration:
    endpointURL: https://0ae89288096e9795bb1a5d327d89aec5.r2.cloudflarestorage.com
    destinationPath: s3://microblog-network-cnpg-storage/v20260414/