apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace microblog-network

helmGlobals:
  chartHome: ../../../../../charts
  
resources:
  - ../../base
  - secrets.yaml
helmCharts:
  - name: redis-ha
    valuesFile: ../../base/helm-values/redis-ha.yaml
    additionalValuesFiles:
      - helm-values/redis-ha.yaml
    releaseName: redis-ha
    version: 4.35.10
    namespace: *namespace
    repo: https://dandydeveloper.github.io/charts
  - name: mastodon
    version: "0.0.0"
    releaseName: mastodon
    namespace: *namespace
    valuesFile: ../../base/helm-values/mastodon.yaml
    additionalValuesFiles:
      - helm-values/mastodon.yaml
  - name: varnish
    version: "0.0.0"
    releaseName: varnish-for-static
    namespace: *namespace
    valuesFile: ../../base/helm-values/varnish-for-static.yaml
    additionalValuesFiles:
      - helm-values/varnish-for-static.yaml
  - name: varnish
    version: "0.0.0"
    releaseName: varnish-for-app
    namespace: *namespace
    valuesFile: ../../base/helm-values/varnish-for-app.yaml
    additionalValuesFiles:
      - helm-values/varnish-for-app.yaml

images:
  - name: ghcr.io/mastodon/mastodon
    newTag: "v4.5.7@sha256:40928319dea8891b26840408452290fcd6e471fcd595fb53f7a9e8a3e3094682"
  - name: ghcr.io/mastodon/mastodon-streaming
    newTag: "v4.5.7@sha256:5d9169475942b11296506299804526c629deddcaf63334a176f51b96d6be9d3d"
  - name: varnish
    newTag: "8.0.0@sha256:0e1132c6e36ff88eabf3dcc51210beb1c3f9d333a361802e027bf4333c8891a9"
    
patches:
  - path: database-cluster.yaml
  # - path: ../../base/patches/redis-ha-haproxy-affinity.yaml
