apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mastodon-secrets-env
  namespace: microblog-network
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: microblog-network/mastodon-secrets-env
  refreshAfter: "1h"
  destination:
    name: mastodon-secrets-env
    create: true
    overwrite: true
