apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport

resources:
  - vault-auth.yaml
  - vault-static-secret.yaml

helmCharts:
  - name: teleport-kube-agent
    version: "18.7.4"
    releaseName: teleport-agent
    namespace: teleport
    valuesFile: helm-values.yaml
    repo: https://charts.releases.teleport.dev
