apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: teleport-join-token
  namespace: teleport
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: teleport/join-token
  refreshAfter: "1h"
  destination:
    name: teleport-join-token
    create: true
    overwrite: true
