apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  labels:
    teleport.dev/enabled: "true"
  annotations:
    teleport.dev/name: tc-argocd
    teleport.dev/port: "443"
    teleport.dev/protocol: https
    teleport.dev/description: "ArgoCD GitOps continuous delivery"
