{{- if .Values.vault.secretsEnv.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "mastodon.fullname" . }}-secrets-env
spec:
  vaultAuthRef: {{ .Values.vault.secretsEnv.vaultAuthRef }}
  mount: {{ .Values.vault.secretsEnv.mount }}
  type: kv-v2
  path: {{ .Values.vault.secretsEnv.path }}
  refreshAfter: {{ .Values.vault.secretsEnv.refreshAfter | quote }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "mastodon.fullname" . }}-web
    {{- range .Values.sidekiq.workers }}
    - kind: Deployment
      name: {{ include "mastodon.fullname" $ }}-sidekiq-{{ .name }}
    {{- end }}
  destination:
    name: {{ include "mastodon.fullname" . }}-secrets-env
    create: true
    overwrite: true
{{- end }}
