{{- if .Values.vault.s3Credentials.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "mastodon.fullname" . }}-s3-credentials
spec:
  vaultAuthRef: {{ .Values.vault.s3Credentials.vaultAuthRef }}
  mount: {{ .Values.vault.s3Credentials.mount }}
  type: kv-v2
  path: {{ .Values.vault.s3Credentials.path }}
  refreshAfter: {{ .Values.vault.s3Credentials.refreshAfter | quote }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "mastodon.fullname" . }}-web
    {{- range .Values.sidekiq.workers }}
    - kind: Deployment
      name: {{ include "mastodon.fullname" $ }}-sidekiq-{{ .name }}
    {{- end }}
  destination:
    name: {{ include "mastodon.fullname" . }}-s3-credentials
    create: true
    overwrite: true
{{- end }}
