apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: argocd/argocd-secrets
  refreshAfter: "1h"
  destination:
    name: argocd-secrets
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/part-of: argocd
