apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: static-client-secrets
  namespace: dex
spec:
  vaultAuthRef: default
  mount: secret
  type: kv-v2
  path: dex/static-client-secrets
  refreshAfter: "1h"
  destination:
    name: static-client-secrets
    create: true
    overwrite: true
