{
 "title": "Traefik Official Kubernetes Dashboard",
 "description": "Official dashboard supporting multiple instances of Traefik on Kubernetes",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(traefik_config_reloads_total, namespace)"
    }
   },
   {
    "name": "entrypoint",
    "query": {
     "query": "label_values(traefik_entrypoint_open_connections, entrypoint)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(traefik_service_open_connections, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{namespace=~\"$namespace\",entrypoint=~\"$entrypoint\"}[1m])) by (namespace, entrypoint)",
     "legendFormat": "{{namespace}} on {{entrypoint}}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",namespace=~\"$namespace\",entrypoint=~\"$entrypoint\"}[5m])) by (namespace, method) + \n sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\", namespace=~\"$namespace\",entrypoint=~\"$entrypoint\"}[5m])) by (namespace, method)) / 2 / \n sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",namespace=~\"$namespace\",entrypoint=~\"$entrypoint\"}[5m])) by (namespace, method)\n",
     "legendFormat": "{{namespace}} on {{method}}"
    }
   ]
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{namespace=~\"$namespace\",service=~\"$service.*\",protocol=\"http\"}[1m])) by (namespace, method, code)",
     "legendFormat": "{{namespace}}:{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Top slow services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace( \n        traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\",service=~\"$service.*\",protocol=\"http\"} / \n          traefik_service_request_duration_seconds_count{namespace=~\"$namespace\",service=~\"$service.*\",protocol=\"http\"},\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)\n\n",
     "legendFormat": "{{namespace}} {{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Most requested services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (namespace,service,code) \n          (rate(traefik_service_requests_total{namespace=~\"$namespace\",service=~\"$service.*\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{namespace}} [{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services failing SLO of 1200ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\n  1 - (sum by (service,namespace)\n    (rate(traefik_service_request_duration_seconds_bucket{le=\"1.2\",namespace=~\"$namespace\",service=~\"$service.*\"}[5m])) / sum by (service,namespace) \n    (rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\",service=~\"$service.*\"}[5m]))\n  ) > 0,\n  \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"\n)",
       "legendFormat": "{{namespace}} on {{service}}"
      }
     ]
    },
    {
     "title": "Services failing SLO of 300ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "label_replace(\n  1 - (sum by (service,namespace)\n    (rate(traefik_service_request_duration_seconds_bucket{le=\"0.3\",namespace=~\"$namespace\",service=~\"$service.*\"}[5m])) / sum by (service,namespace) \n    (rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\",service=~\"$service.*\"}[5m]))\n  ) > 0,\n  \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\"\n)",
       "legendFormat": "{{namespace}} on {{service}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "2xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (namespace,service,method,code) \n          (rate(traefik_service_requests_total{namespace=~\"$namespace\",service=~\"$service.*\",code=~\"2..\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{namespace}} {{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "5xx over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (namespace,service,method,code) \n          (rate(traefik_service_requests_total{namespace=~\"$namespace\",service=~\"$service.*\",code=~\"5..\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{namespace}} {{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Other codes over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (namespace,service,method,code) \n          (rate(traefik_service_requests_total{namespace=~\"$namespace\",service=~\"$service.*\",code!~\"2..|5..\",protocol=\"http\"}[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{namespace}} {{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (namespace,service,method) \n          (rate(traefik_service_requests_bytes_total{namespace=~\"$namespace\",service=~\"$service.*\",protocol=\"http\"}[1m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "{{namespace}} {{method}} on {{service}}"
    }
   ]
  },
  {
   "title": "Connections per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(traefik_service_open_connections{namespace=~\"$namespace\",service=~\"$service.*\"}) by (namespace,service),\n    \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")",
     "legendFormat": "{{namespace}} on {{service}}"
    }
   ]
  },
  {
   "title": "Connections per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{namespace=~\"$namespace\",entrypoint=~\"$entrypoint\"}) by (namespace,entrypoint)\n",
     "legendFormat": "{{namespace}} on {{entrypoint}}"
    }
   ]
  }
 ]
}